server.port=8080
spring.application.name=api-gateway

spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

application.security.jwt.secret-key=${JWT_SECRET}

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${USER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=content-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${CONTENT_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/content/**

spring.cloud.gateway.server.webmvc.routes[2].id=progress-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${PROGRESS_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/progress/**

spring.cloud.gateway.server.webmvc.routes[3].id=chatbot-service
spring.cloud.gateway.server.webmvc.routes[3].uri=${CHATBOT_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/chatbot/**

# Ruta analysis-service — cu filtre pentru stergerea headerelor problematice
spring.cloud.gateway.server.webmvc.routes[4].id=analysis-service
spring.cloud.gateway.server.webmvc.routes[4].uri=${ANALYSIS_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/analysis/**

spring.cloud.gateway.server.webmvc.routes[5].id=flashcard-service
spring.cloud.gateway.server.webmvc.routes[5].uri=${FLASHCARD_SERVICE_URL:http://localhost:8086}
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/flashcards/**


# Filtre globale — sterg headerele problematice pentru uvicorn
spring.cloud.gateway.server.webmvc.default-filters[0]=RemoveRequestHeader=Connection
spring.cloud.gateway.server.webmvc.default-filters[1]=RemoveRequestHeader=Upgrade