spring.application.name=flashcard-service
server.port=8086

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/flashcard_database}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
