spring.application.name=content-service
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/content_database}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

storage.upload-dir=uploads
storage.base-url=${STORAGE_BASE_URL:http://localhost:8081}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
