spring.application.name=progress-service
server.port=8083

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/progress_database}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

content-service.url=${CONTENT_SERVICE_URL:http://localhost:8081}

spring.jpa.open-in-view=false
